version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      #POSTGRES_DB: lucmsdev
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgdevpassword
    volumes:
      - lucms-postgres:/var/lib/postgresql/data
    ports:
      - '5433:5433'

volumes:
  lucms-postgres: