version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgdevpassword
      #POSTGRES_DB: lucmsdev
    volumes:
      - ./db/postgresql:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080